<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule;

use Cmfcmf\OAuthModule\Base\CmfcmfOAuthModule as BaseCmfcmfOAuthModule;

/**
 * Module implementation class.
 */
class CmfcmfOAuthModule extends BaseCmfcmfOAuthModule
{
    // custom enhancements can go here
}
