<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Fri Nov 22 18:59:02 CET 2013.
 */

namespace Cmfcmf\OAuthModule;

use Cmfcmf\OAuthModule\Base\OAuthModuleVersion as BaseOAuthModuleVersion;

/**
 * Version information implementation class.
 */
class OAuthModuleVersion extends BaseOAuthModuleVersion
{
    /**
     * @inheritdoc
     *
     * This adds the authentication capability.
     */
    public function getMetaData()
    {
        $meta = parent::getMetaData();
        $meta['capabilities']['authentication'] = array('version' => '1.0.0');
        $meta['displayname']          = $this->__('OAuth');
        $meta['description']          = $this->__('OAuth module generated by ModuleStudio 0.6.1.');

        return $meta;
    }
}
