<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule;

use Cmfcmf\OAuthModule\Base\RouterFacade as BaseRouterFacade;

/**
 * Url router facade implementation class.
 */
class RouterFacade extends BaseRouterFacade
{
    // here you can customise the data which is provided to the url router.
}
