<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Entity\Validator\Base;

use Cmfcmf\OAuthModule\AbstractValidator as BaseAbstractValidator;

use ServiceUtil;
use Zikula_EntityAccess;
use ZLanguage;

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for mapped id entities.
 */
class MappedIdValidator extends BaseAbstractValidator
{
    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array('message' => '', 'code' => 0, 'debugArray' => array());
        $dom = ZLanguage::getModuleDomain('CmfcmfOAuthModule');
        if (!$this->isValidInteger('id')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('id'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('id', 9)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('id', 9), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('workflowState')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('workflow state'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('userId')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('user id'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotEmpty('userId')) {
            $errorInfo['message'] = __f('Error! Field value must not be 0 (%s).', array('user id'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidUser('userId')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid user id (%s).', array('user id'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('claimedId', 1000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('claimed id', 1000), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('claimedId')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('claimed id'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('provider', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('provider', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('provider')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('provider'), $dom);
            return $errorInfo;
        }
    
        return true;
    }
    
    /**
     * Check for unique values.
     *
     * This method determines if there already exist mapped ids with the same mapped id.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check, true if the given mapped id does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if ($this->entity[$fieldName] == '') {
            return false;
        }
    
        $entityClass = '\\Cmfcmf\\OAuthModule\\Entity\\MappedIdEntity';
        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository($entityClass);
    
        $excludeid = $this->entity['id'];
    
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }
    
    /**
     * Get entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set entity.
     *
     * @param Zikula_EntityAccess $entity.
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }
    
}
