<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Entity\Validator;

use Cmfcmf\OAuthModule\Entity\Validator\Base\UserValidator as BaseUserValidator;

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for user entities.
 */
class UserValidator extends BaseUserValidator
{
    // here you can add custom validation methods or override existing checks
}
