<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * The cmfcmfoauthmoduleObjectState modifier displays the name of a given object's workflow state.
 * Examples:
 *    {$item.workflowState|cmfcmfoauthmoduleObjectState}       {* with visual feedback *}
 *    {$item.workflowState|cmfcmfoauthmoduleObjectState:false} {* no ui feedback *}
 *
 * @param string  $state      Name of given workflow state.
 * @param boolean $uiFeedback Whether the output should include some visual feedback about the state.
 *
 * @return string Enriched and translated workflow state ready for display.
 */
function smarty_modifier_cmfcmfoauthmoduleObjectState($state = 'initial', $uiFeedback = true)
{
    $serviceManager = ServiceUtil::getManager();
    $workflowHelper = new Cmfcmf\OAuthModule\Util\WorkflowUtil($serviceManager, ModUtil::getModule('CmfcmfOAuthModule'));
    $stateInfo = $workflowHelper->getStateInfo($state);

    $result = $stateInfo['text'];
    if ($uiFeedback === true) {
        $result = '<span class="label label-' . $stateInfo['ui'] . '">' . $result . '</span>';
    }

    return $result;
}
