<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Listener;

use Cmfcmf\OAuthModule\Listener\Base\UsersListener as BaseUsersListener;
use Zikula\Core\Event\GenericEvent;

/**
 * Event handler implementation class for events of the Users module.
 */
class UsersListener extends BaseUsersListener
{
    /**
     * Listener for the `module.users.config.updated` event.
     *
     * Occurs after the Users module configuration has been
     * updated via the administration interface.
     *
     * @param GenericEvent $event The event instance.
     */
    public static function configUpdated(GenericEvent $event)
    {
        parent::configUpdated($event);
    }
}
