<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\ContentType;

use Cmfcmf\OAuthModule\ContentType\Base\ItemList as BaseItemList;

/**
 * Generic item list content plugin implementation class.
 */
class ItemList extends BaseItemList
{
    // feel free to extend the content type here
}

function CmfcmfOAuthModule_Api_ContentTypes_itemlist($args)
{
    return new CmfcmfOAuthModule_Api_ContentTypes_itemListPlugin();
}
