<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Form\Plugin;

use Cmfcmf\OAuthModule\Form\Plugin\Base\ItemSelector as BaseItemSelector;

/**
 * Item selector plugin implementation class.
 */
class ItemSelector extends BaseItemSelector
{
    // feel free to add your customisation here
}
