<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Util;

use Cmfcmf\OAuthModule\Util\Base\ListEntriesUtil as BaseListEntriesUtil;

/**
 * Utility implementation class for list field entries related methods.
 */
class ListEntriesUtil extends BaseListEntriesUtil
{
    // feel free to add your own convenience methods here
}
