<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Listener\Base;

use Zikula\Core\Event\GenericEvent;

/**
 * Event handler base class for page-related events.
 */
class PageListener
{
    /**
     * Listener for the `pageutil.addvar_filter` event.
     *
     * Used to override things like system or module stylesheets or javascript.
     * Subject is the `$varname`, and `$event->data` an array of values to be modified by the filter.
     *
     * This single filter can be used to override all css or js scripts or any other var types
     * sent to `PageUtil::addVar()`.
     *
     * @param GenericEvent $event The event instance.
     */
    public static function pageutilAddvarFilter(GenericEvent $event)
    {
        // Simply test with something like
        /*
            if (($key = array_search('system/Users/Cmfcmf/OAuthModule/Resources/public/js/somescript.js', $event->data)) !== false) {
                $event->data[$key] = 'config/javascript/myoverride.js';
            }
        */
    }
    
    /**
     * Listener for the `system.outputfilter` event.
     *
     * Filter type event for output filter HTML sanitisation.
     *
     * @param GenericEvent $event The event instance.
     */
    public static function systemOutputFilter(GenericEvent $event)
    {
    }
}
