<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Listener\Base;

use Zikula\Core\Event\GenericEvent;

/**
 * Event handler implementation class for special purposes and 3rd party api support.
 */
class ThirdPartyListener
{
    /**
     * Listener for pending content items.
     *
     * @param GenericEvent $event The event instance.
     */
    public static function pendingContentListener(GenericEvent $event)
    {
        // nothing required here as no entities use enhanced workflows including approval actions
    }
    
    /**
     * Listener for the `module.content.gettypes` event.
     *
     * This event occurs when the Content module is 'searching' for Content plugins.
     * The subject is an instance of Content_Types.
     * You can register custom content types as well as custom layout types.
     *
     * @param GenericEvent $event The event instance.
     */
    public static function contentGetTypes(GenericEvent $event)
    {
        // intended is using the add() method to add a plugin like below
        $types = $event->getSubject();
        
        // plugin for showing a list of multiple items
        $types->add('CmfcmfOAuthModule_ContentType_ItemList');
    }
    
    /**
     * Listener for the `module.scribite.editorhelpers` event.
     *
     * This occurs when Scribite adds pagevars to the editor page.
     * CmfcmfOAuthModule will use this to add a javascript helper to add custom items.
     *
     * @param GenericEvent $event The event instance.
     */
    public static function getEditorHelpers(GenericEvent $event)
    {
        // intended is using the add() method to add a helper like below
        $helpers = $event->getSubject();
        
        $helpers->add(
            array('module' => 'CmfcmfOAuthModule',
                  'type'   => 'javascript',
                  'path'   => 'modules/Cmfcmf/OAuthModule/Resources/public/js/CmfcmfOAuthModule_finder.js')
        );
    }
    
    /**
     * Listener for the `moduleplugin.tinymce.externalplugins` event.
     *
     * Adds external plugin to TinyMCE.
     *
     * @param GenericEvent $event The event instance.
     */
    public static function getTinyMcePlugins(GenericEvent $event)
    {
        // intended is using the add() method to add a plugin like below
        $plugins = $event->getSubject();
        
        $plugins->add(
            array('name' => 'cmfcmfoauthmodule',
                  'path' => 'modules/Cmfcmf/OAuthModule/Resources/docs/scribite/plugins/TinyMce/vendor/tiny_mce/plugins/cmfcmfoauthmodule/editor_plugin.js'
            )
        );
    }
    
    /**
     * Listener for the `moduleplugin.ckeditor.externalplugins` event.
     *
     * Adds external plugin to CKEditor.
     *
     * @param GenericEvent $event The event instance.
     */
    public static function getCKEditorPlugins(GenericEvent $event)
    {
        // intended is using the add() method to add a plugin like below
        $plugins = $event->getSubject();
        
        $plugins->add(
            array('name' => 'cmfcmfoauthmodule',
                  'path' => 'modules/Cmfcmf/OAuthModule/Resources/docs/scribite/plugins/CKEditor/vendor/ckeditor/plugins/cmfcmfoauthmodule/',
                  'file' => 'plugin.js',
                  'img'  => 'ed_cmfcmfoauthmodule.gif'
            )
        );
    }
}
