<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Controller;

use Cmfcmf\OAuthModule\Controller\Base\AdminController as BaseAdminController;
use ModUtil;
use SecurityUtil;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * This is the Admin controller class providing navigation and interaction functionality.
 */
class AdminController extends BaseAdminController
{
    /**
     * This method is the default function handling the admin area called without defining arguments.
     *
     * @return mixed Output.
     *
     * @throws AccessDeniedHttpException Thrown if the user doesn't have required permissions
     */
    public function indexAction(Request $request)
    {
        unset($request);

        if (!SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            throw new AccessDeniedException();
        }
        return new RedirectResponse(ModUtil::url($this->name, 'admin', 'config'));
    }
}
