<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Controller;

use Cmfcmf\OAuthModule\Controller\Base\AdminController as BaseAdminController;

/**
 * This is the Admin controller class providing navigation and interaction functionality.
 */
class AdminController extends BaseAdminController
{
    // feel free to add your own controller methods here
}
