<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Api;

use Cmfcmf\OAuthModule\Api\Base\AjaxApi as BaseAjaxApi;

/**
 * This is the Ajax api helper class.
 */
class AjaxApi extends BaseAjaxApi
{
    // feel free to add own api methods here
}
