<?php
/**
 * OAuth.
 *
 * @copyright Christian Flach (Cmfcmf)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Christian Flach <cmfcmf.flach@gmail.com>.
 * @link https://www.github.com/cmfcmf/OAuth
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

namespace Cmfcmf\OAuthModule\Form\Handler\Admin;

use Cmfcmf\OAuthModule\Form\Handler\Admin\Base\ConfigHandler as BaseConfigHandler;

/**
 * Configuration handler implementation class.
 */
class ConfigHandler extends BaseConfigHandler
{
    // feel free to extend the base handler class here
}
